### ISSUE TITLE
<title> should contain the posts name

### ISSUE THREAD

**Issue by hecatia-elegua** [nikomatsakis/babysteps#18]
I like your blogposts so much I often save them, which fills in this way:
![image](https://user-images.githubusercontent.com/108802164/230594078-6f1ac3d5-1423-421b-8a86-d8a7009509c4.png)
 so to whomever you decide to hire: should be easy to fix

**Comment by nikomatsakis** [comment]
Oh, geez

**Comment by nikomatsakis** [comment]
Actually, I think this is fixed now!
