### ISSUE TITLE
Blog posts before 2016 not showing up (error 404)

### ISSUE THREAD

**Issue by dlight** [nikomatsakis/babysteps#25]
So, after the Hugo migration, the earliest post is this one:

https://smallcultfollowing.com/babysteps/blog/2016/11/02/associated-type-constructors-part-1-basic-concepts-and-introduction/

And earlier posts are returning 404 error, such as this iconic one:

http://smallcultfollowing.com/babysteps/blog/2012/11/18/imagine-never-hearing-the-phrase-aliasable/

That's unfortunate!

**Comment by nikomatsakis** [comment]
ACK! Oh no!

**Comment by nikomatsakis** [comment]
should be in the history...
