### ISSUE TITLE
By-reference markdown links are not rendered

### ISSUE THREAD

**Issue by dlight** [nikomatsakis/babysteps#26]
After the Hugo migrations, [by-reference markdown links](https://www.ii.com/links-footnotes-markdown/#by-reference-link-example-2) `[like this][tag] .. [tag]: http://..` are not rendered (but regular links `[like this](http://..)` are)

Seen here https://smallcultfollowing.com/babysteps/blog/2020/12/30/the-more-things-change/

Additionally, `{{ site.baseurl }}` is not expanded (perhaps because Hugo templating doesn't use `{{..}}`)

**Comment by nikomatsakis** [comment]
I wonder if those two things are connected

**Comment by nikomatsakis** [comment]
Thanks!

**Comment by nikomatsakis** [comment]
I think I resolved this.
