### ISSUE TITLE
When acessing via http://, site loses all CSS due to CORS issue

### ISSUE THREAD

**Issue by dlight** [nikomatsakis/babysteps#29]
When you access

http://smallcultfollowing.com/babysteps/blog/2023/09/19/new-layout/

Rather than

https://smallcultfollowing.com/babysteps/blog/2023/09/19/new-layout/

The website loses all styling because of a CORS issue: the stylesheet is always served through https:// even if we access the site through http://, and the console says:

> “https://smallcultfollowing.com/babysteps/scss/main.2a3103be5585f05b9867e22fcdd577d414a740b6095368826234518e9a700352.css” is not eligible for integrity checks since it’s neither CORS-enabled nor same-origin.

The best fix here is probably to have a http:// to https:// redirect (with 301 status code, moved permanently), and never serve any content under http://. I don't know if Hugo has some specific support for this or if you need to configure some other part of the stack (but I think it's the latter).

Another fix is to ensure that, when you access the page through an unsecured connection, all other resources would be served using http:// as well.

If either solutions are too bothersome, a workaround is to add `crossorigin="anonymous"` to the `<link>` tag, as seen [here](https://stackoverflow.com/a/35323436) and [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin).

**Comment by nikomatsakis** [comment]
I thought that I was already redirecting http to https -- apparently not.

**Comment by nikomatsakis** [comment]
Thanks!

**Comment by nikomatsakis** [comment]
@dlight I *think* this is fixed now, can you confirm?

**Comment by dlight** [comment]
Yes the http to https redirect is working now!
