### ISSUE TITLE
Confusing paragraph

### ISSUE THREAD

**Issue by istankovic** [nikomatsakis/babysteps#31]
While reading "Polonius revisited, part 1", I came across this part:

https://github.com/nikomatsakis/babysteps/blob/7697fffb0eb3d487b96b25b06fb447bc79a51d9f/content/blog/2023-09-22-polonius-part-1.markdown?plain=1#L266C1-L266C715

and ended up confused. Shouldn't the references (heh) to the `L1` loan in that paragraph point to the `L0` loan?

**Comment by nikomatsakis** [comment]
You are correct. I've pushed some changes that hopefully clarify things!

**Comment by istankovic** [comment]
Thanks, that's definitely much clearer now. :purple_heart:
