### ISSUE TITLE
Feedback on More thoughts on claiming

### ISSUE THREAD

**Issue by sgued** [nikomatsakis/babysteps#44]
I wonder, with `Rc` and `Arc` being `Claim`, would the following ever call clone, or would it be optimized out as a move/noop? If not, that could significantly impact the performance of existing Rust code, but at the same time doing it seems like it's adding optimisations that are observable.

```rust
let a = Rc::new(true);
let b = a;
```

```rust
let a = Arc::new(true);
let b = a;
```

**Comment by bakhtiyarneyman** [comment]
> Autoclaim would not apply to the last use of a variable. So x = y only introduces a call to claim if it is needed to prevent an error. This avoids unnecessary reference counting.

https://smallcultfollowing.com/babysteps/blog/2024/06/21/claim-auto-and-otherwise/

**Comment by nikomatsakis** [comment]
My expectation is that it would not clone unless `a` were used again.
